Stars data inside HouseCard and Reviews
haikuacademy/B11G03-airbnb-react pull request #45
Opened 2024-03-04 05:48 UTC by AlvesDv

2024-03-04 06:30 UTC, ynotrusso requested changes

2024-03-04 06:30 UTC, ynotrusso commented on src/components/HouseCard.jsx
> +import { faStar } from '@fortawesome/free-regular-svg-icons'
wrong package, must use solid

2024-03-04 06:30 UTC, ynotrusso commented on src/components/HouseCard.jsx
> +          <p className="font-bold">Phuket, Thailand</p>
why change everything to paragraphs? You should only add icons in this branch

2024-03-04 06:37 UTC, AlvesDv commented on src/components/HouseCard.jsx
> +          <p className="font-bold">Phuket, Thailand</p>
Should I reverse this changes?

2024-03-04 06:56 UTC, AlvesDv commented on src/components/HouseCard.jsx
> +import { faStar } from '@fortawesome/free-regular-svg-icons'
Done  ⭐️

2024-03-05 06:57 UTC, ynotrusso requested changes

2024-03-05 06:57 UTC, ynotrusso commented on src/components/HouseCard.jsx
> +          <p className="font-bold">Phuket, Thailand</p>
Yes :)

2024-03-05 07:13 UTC, AlvesDv commented on src/components/HouseCard.jsx
> +          <p className="font-bold">Phuket, Thailand</p>
Done  👍

2024-03-06 06:12 UTC, ynotrusso approved these changes

2024-03-06 07:13 UTC, ynotrusso approved these changes

2024-03-06 07:13 UTC, merged